package postgres

import (
	"context"
	"crypto/pbkdf2"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"testing"
	"time"

	"github.com/hakanaltindag/svcdoctor/internal/domain"
)

// The PostgreSQL credential leak matrix.
//
// Phase 4.4b is the second place in svcdoctor where a secret becomes bytes. This
// file asserts the exact absence of every value that exchange touches — the
// password, both nonces, the salt, all six derived keys and signatures, the auth
// message, the client proof, and the server's own prose — from evidence, from a
// report in both output modes, from returned errors, and from every fmt verb on
// every exported type this package hands upward.
//
// # Why it is not vacuous
//
// Two controls. TestSuccessfulAuthenticationReallySentTheProof proves the peer
// received a real client proof, so "the proof is absent from the report" is a
// statement about the report rather than about an exchange that never happened.
// And canaryLeaked below is exercised against a value that *is* present — the
// endpoint — so a broken search would fail the control before it passed the
// matrix.

// scramCanaries is every sensitive intermediate of one exchange, recomputed
// independently of the production code from what the peer actually observed.
type scramCanaries struct {
	password        string
	clientNonce     string
	serverNonce     string
	salt            string
	saltedPassword  string
	clientKey       string
	storedKey       string
	clientSignature string
	clientProof     string
	serverKey       string
	serverSignature string
	authMessage     string
}

// all returns every canary with a label, for a table-driven assertion.
func (c scramCanaries) all() map[string]string {
	return map[string]string{
		"password":         c.password,
		"client nonce":     c.clientNonce,
		"server nonce":     c.serverNonce,
		"salt":             c.salt,
		"salted password":  c.saltedPassword,
		"client key":       c.clientKey,
		"stored key":       c.storedKey,
		"client signature": c.clientSignature,
		"client proof":     c.clientProof,
		"server key":       c.serverKey,
		"server signature": c.serverSignature,
		"auth message":     c.authMessage,
	}
}

// deriveCanaries recomputes the exchange from the bytes the peer received.
//
// The client nonce is generated by crypto/rand at run time, so it is recovered
// from what svcdoctor actually sent rather than assumed — which also means these
// canaries describe the real exchange and not a parallel one.
func deriveCanaries(t *testing.T, peer *pgPeer) scramCanaries {
	t.Helper()

	clientFirstBare, serverFirst, clientFinal := peer.exchange()
	if clientFirstBare == "" || serverFirst == "" || clientFinal == "" {
		t.Fatal("the fixture did not observe a complete SCRAM exchange")
	}

	clientNonce := attrValue(clientFirstBare, 'r')
	if clientNonce == "" {
		t.Fatalf("no client nonce in %q", clientFirstBare)
	}
	withoutProof := clientFinal
	if i := strings.Index(clientFinal, ",p="); i >= 0 {
		withoutProof = clientFinal[:i]
	}
	authMessage := clientFirstBare + "," + serverFirst + "," + withoutProof

	salted, err := pbkdf2.Key(sha256.New, canaryPassword, fixtureSalt(), fixtureIterations, sha256.Size)
	if err != nil {
		t.Fatalf("pbkdf2: %v", err)
	}
	clientKey := hmacSum(salted, []byte("Client Key"))
	storedKey := sha256.Sum256(clientKey)
	clientSignature := hmacSum(storedKey[:], []byte(authMessage))
	serverKey := hmacSum(salted, []byte("Server Key"))
	serverSignature := hmacSum(serverKey, []byte(authMessage))

	b64 := base64.StdEncoding.EncodeToString
	return scramCanaries{
		password:        canaryPassword,
		clientNonce:     clientNonce,
		serverNonce:     attrValue(withoutProof, 'r'),
		salt:            b64(fixtureSalt()),
		saltedPassword:  b64(salted),
		clientKey:       b64(clientKey),
		storedKey:       b64(storedKey[:]),
		clientSignature: b64(clientSignature),
		clientProof: fixtureClientProof(
			canaryPassword, fixtureIterations, clientFirstBare, serverFirst, withoutProof),
		serverKey:       b64(serverKey),
		serverSignature: b64(serverSignature),
		authMessage:     authMessage,
	}
}

// pgReportFrom assembles a report from a builder, in the requested output mode.
func pgReportFrom(t *testing.T, builder *domain.GraphBuilder) domain.Report {
	t.Helper()

	graph := freeze(t, builder)

	run, err := domain.NewRunMetadata("0.1.0", time.Now(), time.Second, "postgres")
	if err != nil {
		t.Fatalf("NewRunMetadata: %v", err)
	}
	target, err := domain.NewTarget(canaryHost + ":5432")
	if err != nil {
		t.Fatalf("NewTarget: %v", err)
	}
	vantage, err := domain.NewLocalVantage("pg-runner-canary.local")
	if err != nil {
		t.Fatalf("NewLocalVantage: %v", err)
	}
	reportSecurity, err := domain.NewReportSecurity(domain.OutputModeLocalFull, false, false)
	if err != nil {
		t.Fatalf("NewReportSecurity: %v", err)
	}

	report, err := domain.NewReport(domain.ReportInput{
		Run: run, Target: target, Vantage: vantage, Graph: graph, Security: reportSecurity,
	})
	if err != nil {
		t.Fatalf("NewReport: %v", err)
	}
	return report
}

// TestNoSCRAMIntermediateReachesAnyOutput is the matrix.
func TestNoSCRAMIntermediateReachesAnyOutput(t *testing.T) {
	result, builder, peer := verifiedTLS(t, scramScript{})

	session, err := Authenticate(
		context.Background(), builder, result, canaryCredential(t), AuthParams{})
	if err != nil || session == nil {
		t.Fatalf("Authenticate: %v", err)
	}
	t.Cleanup(func() { _ = session.Close() })

	canaries := deriveCanaries(t, peer)

	// The control: the exchange really happened, with these values.
	sent := string(peer.afterStartup())
	if !strings.Contains(sent, canaries.clientProof) {
		t.Fatal("the peer did not receive the client proof this test asserts is absent elsewhere")
	}
	if !strings.Contains(sent, canaries.clientNonce) {
		t.Fatal("the peer did not receive the client nonce")
	}

	report := pgReportFrom(t, builder)
	node := authNode(t, builder)

	surfaces := map[string]string{
		"report JSON":         encodeJSON(t, report),
		"graph nodes":         fmt.Sprintf("%+v", freeze(t, builder).Nodes()),
		"node attributes":     fmt.Sprintf("%+v", node.Attributes()),
		"node JSON":           encodeJSON(t, node),
		"authentication node": fmt.Sprintf("%+v", node),
	}

	// Every verb, including the ones that are "wrong" for a struct. That is the
	// interesting case rather than a sloppy one: fmt handles an unsupported verb
	// through its badVerb path, which sets an internal erroring flag and then
	// prints the operand by reflection — a walk that can read unexported fields.
	// internal/security/secret.go documents the same hazard, and this is where
	// the types built on top of it get held to it.
	//
	// The format strings are built at run time so that go vet does not reject
	// the deliberately mismatched verbs.
	for _, verb := range []string{"%v", "%+v", "%#v", "%q", "%x", "%s", "%d"} {
		surfaces["session "+verb] = fmt.Sprintf(verb, session)
		surfaces["startup result "+verb] = fmt.Sprintf(verb, result)
		surfaces["node "+verb] = fmt.Sprintf(verb, node)
	}

	for surface, text := range surfaces {
		for label, canary := range canaries.all() {
			if canary == "" {
				t.Fatalf("canary %q was not computed", label)
			}
			if strings.Contains(text, canary) {
				t.Errorf("%s contains the %s", surface, label)
			}
		}
	}
}

// TestLeakSearchActuallyWorks is the control for the search itself.
//
// A matrix that scans for absence proves nothing if the scan is broken. This
// asserts the same surfaces *do* contain a value that belongs there, so a
// mistake in how the report is rendered or searched fails here first.
func TestLeakSearchActuallyWorks(t *testing.T) {
	result, builder, _ := verifiedTLS(t, scramScript{})

	session, err := Authenticate(
		context.Background(), builder, result, canaryCredential(t), AuthParams{})
	if err != nil || session == nil {
		t.Fatalf("Authenticate: %v", err)
	}
	t.Cleanup(func() { _ = session.Close() })

	encoded := encodeJSON(t, pgReportFrom(t, builder))
	for _, present := range []string{canaryHost, "SCRAM-SHA-256", "postgres.authentication"} {
		if !strings.Contains(encoded, present) {
			t.Errorf("the report does not contain %q, so the absence assertions are unreliable", present)
		}
	}
}

// TestServerProseNeverReachesEvidence plants identity-rich text in every
// ErrorResponse field the protocol allows and proves none of it survives.
//
// The M field of a real PostgreSQL rejection carries the role, the database and
// svcdoctor's own NAT-translated source address as the server saw it — an
// address that appears nowhere else in the report, which structural redaction
// therefore cannot pseudonymize.
func TestServerProseNeverReachesEvidence(t *testing.T) {
	const (
		canaryMessage = "MESSAGE-CANARY-password-authentication-failed"
		canaryDetail  = "DETAIL-CANARY-/var/lib/postgresql/pg_hba.conf"
		canaryHint    = "HINT-CANARY-contact-dba@corp.internal"
		canaryNAT     = "192.168.65.1"
	)

	result, builder, _ := verifiedTLS(t, scramScript{
		respondFinal: func(w io.Writer, _ []byte) {
			_, _ = w.Write(errorFrame(
				"S", "FATAL",
				"V", "FATAL",
				"C", "28P01",
				"M", canaryMessage+` user "payments_writer" from host "`+canaryNAT+`"`,
				"D", canaryDetail,
				"H", canaryHint,
				"F", "auth.c",
				"L", "317",
				"R", "auth_failed",
			))
		},
	})

	if _, err := Authenticate(
		context.Background(), builder, result, canaryCredential(t), AuthParams{}); err != nil {
		t.Fatalf("Authenticate: %v", err)
	}

	node := requireNode(t, builder,
		domain.StateFail, domain.FailureAuthCredentialsRejected)

	// The two whitelisted fields survive, which is the control.
	if got := attrString(t, node, AttrSQLState); got != "28P01" {
		t.Errorf("sqlstate = %q, want 28P01", got)
	}
	if got := attrString(t, node, AttrErrorSeverity); got != "FATAL" {
		t.Errorf("severity = %q, want FATAL", got)
	}

	encoded := encodeJSON(t, pgReportFrom(t, builder))
	surfaces := []string{
		encoded,
		fmt.Sprintf("%+v", node),
		fmt.Sprintf("%+v", node.Attributes()),
	}
	for _, text := range surfaces {
		for _, canary := range []string{
			canaryMessage, canaryDetail, canaryHint, canaryNAT,
			"auth.c", "auth_failed", "pg_hba", "dba@corp.internal",
		} {
			if strings.Contains(text, canary) {
				t.Errorf("server prose %q reached output", canary)
			}
		}
	}
}

// TestAuthenticatedSessionExposesNoCredential proves the type-state carries
// nothing that could be read back.
func TestAuthenticatedSessionExposesNoCredential(t *testing.T) {
	result, builder, peer := verifiedTLS(t, scramScript{})

	session, err := Authenticate(
		context.Background(), builder, result, canaryCredential(t), AuthParams{})
	if err != nil || session == nil {
		t.Fatalf("Authenticate: %v", err)
	}
	t.Cleanup(func() { _ = session.Close() })

	canaries := deriveCanaries(t, peer)

	// Every accessor the type offers, rendered.
	rendered := fmt.Sprintf("%v %v %v %v",
		session.Endpoint(), session.Address(), session.Evidence(), session.Channel())
	if id, ok := session.ChannelEvidence(); ok {
		rendered += " " + string(id)
	}

	for label, canary := range canaries.all() {
		if strings.Contains(rendered, canary) {
			t.Errorf("an AuthenticatedSession accessor exposed the %s", label)
		}
	}
	if strings.Contains(rendered, "payments_writer") {
		t.Error("an AuthenticatedSession accessor exposed the role")
	}
}

// TestErrorsCarryNoSecret walks the error paths a caller can actually receive.
func TestErrorsCarryNoSecret(t *testing.T) {
	result, builder, _ := verifiedTLS(t, scramScript{})

	_, err := Authenticate(context.Background(), builder, result,
		credentialFor(t, "elsewhere.internal", 5432, canaryPassword), AuthParams{})
	if err == nil {
		t.Fatal("expected an endpoint mismatch error")
	}
	for _, verb := range []string{
		fmt.Sprintf("%v", err), fmt.Sprintf("%+v", err),
		fmt.Sprintf("%#v", err), fmt.Sprintf("%q", err),
	} {
		if strings.Contains(verb, canaryPassword) {
			t.Errorf("an error rendered with a verb leaked the password: %s", verb)
		}
	}
}

func encodeJSON(t *testing.T, v any) string {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	return string(b)
}
